GET http://localhost:8080/health

### Create Customer

POST http://localhost:8080/customers
Content-Type: application/json

{
    "customer_id": 190902502,
    "first_name": "John",
    "middle_name": "Doe",
    "last_name": "Smith",
    "date_of_birth": "1990-01-01"
}